import type { ChefProfile } from "../types";

const ISO = "2026-01-01T00:00:00.000Z";

export const SEED_CHEFS: ChefProfile[] = [
 {
  id: "maya",
  userId: "u-maya",
  displayName: "Chef Maya",
  bio:
   "Former line cook at Bestia. I batch-prep macro-balanced meals every Sunday so you can hit your goals without thinking about it.",
  specialty: "High-protein weekly prep",
  location: "Echo Park, LA",
  neighborhood: "Echo Park · 1.2 mi",
  avatarGradient: ["#1F2937", "#4B5563"],
  initials: "M",
  pickupEnabled: true,
  deliveryEnabled: true,
  deliveryFee: 4.99,
  customRequestsEnabled: true,
  minimumCustomOrderAmount: 80,
  rating: 4.92,
  reviewCount: 412,
  verificationStatus: "verified",
  payoutStatus: "ready",
  verified: true,
  featured: true,
  badges: ["Verified Chef", "CFPM Certified", "Kitchen Reviewed"],
  createdAt: ISO,
  updatedAt: ISO,
 },
 {
  id: "andre",
  userId: "u-andre",
  displayName: "Chef Andre",
  bio:
   "Five kids of my own. I cook the kind of food that fills a house: taco nights, pot roasts, gumbo Sundays.",
  specialty: "Family dinners & comfort meals",
  location: "Highland Park, LA",
  neighborhood: "Highland Park · 2.4 mi",
  avatarGradient: ["#7A4421", "#3B1E0E"],
  initials: "A",
  pickupEnabled: true,
  deliveryEnabled: false,
  customRequestsEnabled: false,
  rating: 4.86,
  reviewCount: 218,
  verificationStatus: "verified",
  payoutStatus: "ready",
  verified: true,
  badges: ["Verified Chef", "Kitchen Reviewed", "Family Meals"],
  createdAt: ISO,
  updatedAt: ISO,
 },
 {
  id: "lina",
  userId: "u-lina",
  displayName: "Chef Lina",
  bio:
   "Plant-forward. Everything is gluten-free by default. I post the week's menu on Thursday at 6pm.",
  specialty: "Vegan & gluten-free meal prep",
  location: "Silver Lake, LA",
  neighborhood: "Silver Lake · 0.8 mi",
  avatarGradient: ["#5E7A3A", "#2E3D1A"],
  initials: "L",
  pickupEnabled: true,
  deliveryEnabled: true,
  deliveryFee: 3.99,
  customRequestsEnabled: true,
  minimumCustomOrderAmount: 60,
  rating: 4.95,
  reviewCount: 367,
  verificationStatus: "verified",
  payoutStatus: "ready",
  verified: true,
  featured: true,
  badges: ["Verified Chef", "Food Handler", "Vegan Friendly"],
  createdAt: ISO,
  updatedAt: ISO,
 },
 {
  id: "rosa",
  userId: "u-rosa",
  displayName: "Chef Rosa",
  bio:
   "Abuela-style Latin meal prep adobo, mojo, big-batch arroz. Cooking with care every week.",
  specialty: "Latin-inspired weekly prep",
  location: "Boyle Heights, LA",
  neighborhood: "Boyle Heights · 3.1 mi",
  avatarGradient: ["#A56247", "#5E2A1A"],
  initials: "R",
  pickupEnabled: false,
  deliveryEnabled: true,
  deliveryFee: 5.99,
  customRequestsEnabled: true,
  minimumCustomOrderAmount: 70,
  rating: 4.81,
  reviewCount: 156,
  verificationStatus: "verified",
  payoutStatus: "ready",
  verified: true,
  badges: ["Verified Chef", "Delivery"],
  createdAt: ISO,
  updatedAt: ISO,
 },
 {
  id: "kim",
  userId: "u-kim",
  displayName: "Chef Kim",
  bio:
   "Lunch service for the desk crew. Cold bowls and grain bowls dropped at the office by 11.",
  specialty: "Cold lunch bowls for the office",
  location: "DTLA, LA",
  neighborhood: "DTLA · 2.0 mi",
  avatarGradient: ["#5E8775", "#28443A"],
  initials: "K",
  pickupEnabled: true,
  deliveryEnabled: true,
  deliveryFee: 3.49,
  customRequestsEnabled: false,
  rating: 4.78,
  reviewCount: 92,
  verificationStatus: "verified",
  payoutStatus: "ready",
  verified: true,
  badges: ["Verified Chef", "Cold Meals"],
  createdAt: ISO,
  updatedAt: ISO,
 },
 {
  id: "jordan",
  userId: "u-jordan",
  displayName: "Chef Jordan",
  bio: "New to Mealed. Cheap, lean, no-nonsense meal prep for everyday lifters.",
  specialty: "Budget fitness meal prep",
  location: "Long Beach",
  neighborhood: "Long Beach · 6.4 mi",
  avatarGradient: ["#7A6034", "#3B2E18"],
  initials: "J",
  pickupEnabled: true,
  deliveryEnabled: false,
  customRequestsEnabled: true,
  minimumCustomOrderAmount: 50,
  rating: null,
  reviewCount: 0,
  verificationStatus: "in_review",
  payoutStatus: "pending",
  verified: false,
  badges: ["New Chef", "Pickup"],
  createdAt: ISO,
  updatedAt: ISO,
 },
];
